### ISSUE TITLE
#1217 is broken with `make install` in ruby/ruby

### ISSUE THREAD

**Issue by hsbt** [ruby/rdoc#1221]
@flavorjones @st0012 

#1217 is broken with `make install` of `ruby/ruby`. I reverted that commit at https://github.com/ruby/ruby/commit/0fe82ae087130d7f360cc0607be93995cedbdb16

https://github.com/ruby/actions/actions/runs/12108034481/job/33755653615#step:23:1031

```
/home/runner/work/actions/actions/snapshot-master/lib/rdoc/code_object.rb:322:in 'RDoc::CodeObject#parent': undefined method 'find_class_or_module' for nil (NoMethodError)
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/code_object/class_module.rb:342:in 'RDoc::ClassModule#marshal_dump'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/store.rb:878:in 'Marshal.dump'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/store.rb:878:in 'block in RDoc::Store#save_class'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/store.rb:877:in 'IO.open'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/store.rb:877:in 'RDoc::Store#save_class'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/store.rb:763:in 'block in RDoc::Store#save'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/store.rb:762:in 'Array#each'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/store.rb:762:in 'RDoc::Store#save'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/generator/ri.rb:27:in 'RDoc::Generator::RI#generate'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/rdoc.rb:528:in 'block in RDoc::RDoc#generate'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/rdoc.rb:522:in 'Dir.chdir'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/rdoc.rb:522:in 'RDoc::RDoc#generate'
	from /home/runner/work/actions/actions/snapshot-master/lib/rdoc/rdoc.rb:501:in 'RDoc::RDoc#document'
	from ./tool/rdoc-srcdir:27:in '<main>'
```

Can you look that?

**Comment by flavorjones** [comment]
Sorry for the trouble. I'll investigate in the morning.

**Comment by hsbt** [comment]
Thanks to your work. I will sync this feature when issue is resolved.

**Comment by st0012** [comment]
> Note that this bug is showing up in the ruby/actions CI job where RDocs are generated twice in a row; the second time fails when it #marshal_loads the classes saved during the first run.

Ah I was wondering why I couldn't reproduce the issue locally 😭
