### ISSUE TITLE
missing aref_prefix for RDoc::SingleClass (NotImplementedError)

### ISSUE THREAD

**Issue by voxik** [ruby/rdoc#311]
I am installing net-ldap-0.6.1.gem using command

```
gem install -V --local --install-dir ./usr/share/gems --bindir ./usr/bin --force --document=ri,rdoc /builddir/build/SOURCES/net-ldap-0.6.1.gem
```

but it fails when generating documentation with error:

```
/usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/class_module.rb:173:in `aref_prefix': missing aref_prefix for RDoc::SingleClass (NotImplementedError)
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/class_module.rb:181:in `aref'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/template/darkfish/class.rhtml:47:in `block in generate_class'
    from /usr/share/ruby/erb.rb:850:in `eval'
    from /usr/share/ruby/erb.rb:850:in `result'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:724:in `template_result'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:703:in `block in render_template'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:698:in `open'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:698:in `open'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:698:in `render_template'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:351:in `generate_class'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:371:in `block in generate_class_files'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:368:in `each'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:368:in `generate_class_files'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/generator/darkfish.rb:245:in `generate'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/rubygems_hook.rb:137:in `block in document'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/rubygems_hook.rb:134:in `chdir'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/rubygems_hook.rb:134:in `document'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/rubygems_hook.rb:196:in `generate'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/rubygems_hook.rb:55:in `each'
    from /usr/share/gems/gems/rdoc-4.1.0/lib/rdoc/rubygems_hook.rb:55:in `generation_hook'
    from /usr/share/rubygems/rubygems/dependency_installer.rb:400:in `call'
    from /usr/share/rubygems/rubygems/dependency_installer.rb:400:in `block (2 levels) in install'
    from /usr/share/rubygems/rubygems/dependency_installer.rb:399:in `each'
    from /usr/share/rubygems/rubygems/dependency_installer.rb:399:in `block in install'
    from /usr/share/rubygems/rubygems/dependency_installer.rb:353:in `in_background'
    from /usr/share/rubygems/rubygems/dependency_installer.rb:398:in `install'
    from /usr/share/rubygems/rubygems/commands/install_command.rb:219:in `install_gem'
    from /usr/share/rubygems/rubygems/commands/install_command.rb:263:in `block in install_gems'
    from /usr/share/rubygems/rubygems/commands/install_command.rb:259:in `each'
    from /usr/share/rubygems/rubygems/commands/install_command.rb:259:in `install_gems'
    from /usr/share/rubygems/rubygems/commands/install_command.rb:171:in `execute'
    from /usr/share/rubygems/rubygems/command.rb:305:in `invoke_with_build_args'
    from /usr/share/rubygems/rubygems/command_manager.rb:167:in `process_args'
    from /usr/share/rubygems/rubygems/command_manager.rb:137:in `run'
    from /usr/share/rubygems/rubygems/gem_runner.rb:54:in `run'
    from /usr/bin/gem:21:in `<main>'
```

**Comment by javlc** [comment]
Error still happening:

I did a ```gem update --system``` before doing a ```gem update```, and the issue appeared all the same.

```
Updating rouge
Fetching: rouge-1.10.1.gem (100%)
Successfully installed rouge-1.10.1
Parsing documentation for rouge-1.10.1
Installing ri documentation for rouge-1.10.1
Installing darkfish documentation for rouge-1.10.1
C:/tools/ruby21/lib/ruby/2.1.0/rdoc/class_module.rb:173:in `aref_prefix': missing aref_prefix for RDoc::SingleClass
 (NotImplementedError)
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/class_module.rb:181:in `aref'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/template/darkfish/class.rhtml:47:in `block in generate_c
lass'
        from C:/tools/ruby21/lib/ruby/2.1.0/erb.rb:850:in `eval'
        from C:/tools/ruby21/lib/ruby/2.1.0/erb.rb:850:in `result'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:724:in `template_result'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:703:in `block in render_template'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:698:in `open'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:698:in `open'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:698:in `render_template'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:351:in `generate_class'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:371:in `block in generate_class_files'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:368:in `each'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:368:in `generate_class_files'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/generator/darkfish.rb:245:in `generate'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/rubygems_hook.rb:137:in `block in document'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/rubygems_hook.rb:134:in `chdir'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/rubygems_hook.rb:134:in `document'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/rubygems_hook.rb:196:in `generate'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/rubygems_hook.rb:55:in `each'
        from C:/tools/ruby21/lib/ruby/2.1.0/rdoc/rubygems_hook.rb:55:in `generation_hook'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:189:in `call'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:189:in `block in install'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:188:in `each'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:188:in `install'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/dependency_installer.rb:405:in `install'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/commands/update_command.rb:213:in `update_gem'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/commands/update_command.rb:225:in `block in update_g
ems'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/commands/update_command.rb:224:in `each'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/commands/update_command.rb:224:in `update_gems'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/commands/update_command.rb:100:in `execute'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/command.rb:310:in `invoke_with_build_args'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:169:in `process_args'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:139:in `run'
        from C:/tools/ruby21/lib/ruby/site_ruby/2.1.0/rubygems/gem_runner.rb:55:in `run'
        from C:/tools/ruby21/bin/gem:21:in `<main>'
```

**Comment by Ezerbeth** [comment]
Same error, FreeBSD. Updating makes no difference.

**Comment by lferro9000** [comment]
Installing darkfish documentation for rgen-0.8.0
/usr/lib/ruby/2.1.0/rdoc/class_module.rb:173:in `aref_prefix': missing aref_prefix for RDoc::SingleClass (NotImplementedError)
[...]
Mac OS X El Captain 10.11.5
