### ISSUE TITLE
Invalid class or module definition

### ISSUE THREAD

**Issue by jasonatball** [ruby/rdoc#568]
I help maintain [qtbindings](https://github.com/ryanmelt/qtbindings) for our [COSMOS](https://github.com/BallAerospace/COSMOS) project. It seems rdoc 6.0.0 is no longer able to parse qtbindings. When I try running it against the code base I get an error on the following line:

```
module Qt
  class Base
    def **(a)
      return Qt::**(self, a) # <- RDoc 5.1.0 is fine with this, RDoc 6.0.0 is not
    end
  end
end
```

This is the error reported:

```
C:\git>rdoc -v
6.0.0

C:\git>rdoc qtbindings\lib\Qt\qtruby4.rb
Parsing sources...
100% [ 1/ 1]  qtbindings\lib\Qt\qtruby4.rb
RDoc::Parser::Ruby failure around line 100 of
qtbindings\lib\Qt\qtruby4.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  C:/Ruby242-x64/bin/ruby.exe -c qtbindings\lib\Qt\qtruby4.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

        (RDoc::Error) Invalid class or module definition: Qt

uh-oh! RDoc had a problem:
Invalid class or module definition: Qt

run with --debug for full backtrace
```

**Comment by aycabta** [comment]
Please show error log with `--debug` option.

**Comment by jasonatball** [comment]
```
C:\git\qtbindings>rdoc lib\Qt\qtruby4.rb --debug
Parsing sources...
100% [ 1/ 1]  lib\Qt\qtruby4.rb
RDoc::Parser::Ruby failure around line 100 of
lib\Qt\qtruby4.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  C:/Ruby242-x64/bin/ruby.exe -c lib\Qt\qtruby4.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

        (RDoc::Error) Invalid class or module definition: Qt

C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:376:in `get_class_or_module'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:882:in `parse_constant'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1784:in `parse_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1395:in `block in parse_method_params_and_body'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby_tools.rb:137:in `token_listener'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1373:in `parse_method_params_and_body'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1356:in `parse_method'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1733:in `parse_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:823:in `parse_class_regular'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:765:in `parse_class'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1727:in `parse_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1593:in `parse_module'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1730:in `parse_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1933:in `parse_top_level_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:2067:in `block in scan'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:2065:in `catch'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:2065:in `scan'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:367:in `parse_file'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:419:in `block in parse_files'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:417:in `map'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:417:in `parse_files'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:488:in `document'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/exe/rdoc:20:in `<top (required)>'
        C:/Ruby242-x64/bin/rdoc:23:in `load'
        C:/Ruby242-x64/bin/rdoc:23:in `<main>'
Invalid class or module definition: Qt
C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:376:in `get_class_or_module'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:882:in `parse_constant'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1784:in `parse_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1395:in `block in parse_method_params_and_body'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby_tools.rb:137:in `token_listener'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1373:in `parse_method_params_and_body'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1356:in `parse_method'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1733:in `parse_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:823:in `parse_class_regular'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:765:in `parse_class'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1727:in `parse_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1593:in `parse_module'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1730:in `parse_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:1933:in `parse_top_level_statements'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:2067:in `block in scan'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:2065:in `catch'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/parser/ruby.rb:2065:in `scan'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:367:in `parse_file'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:419:in `block in parse_files'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:417:in `map'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:417:in `parse_files'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/lib/rdoc/rdoc.rb:488:in `document'
        C:/Ruby242-x64/lib/ruby/gems/2.4.0/gems/rdoc-6.0.0/exe/rdoc:20:in `<top (required)>'
        C:/Ruby242-x64/bin/rdoc:23:in `load'
        C:/Ruby242-x64/bin/rdoc:23:in `<main>'
```

**Comment by jasonatball** [comment]
```
C:\git\qtbindings>C:/Ruby242-x64/bin/ruby.exe -c lib\Qt\qtruby4.rb
Syntax OK
```
