### ISSUE TITLE
RDoc::Markdown.parse crashes with invalid footnote

### ISSUE THREAD

**Issue by zelivans** [ruby/rdoc#656]
The third bug found by fuzzing rdoc markdown, similar to https://github.com/ruby/rdoc/issues/654.

## Raw crash
```
/shared/rdoc/lib/rdoc/markdown.rb:802:in `block in parse': undefined method `parts' for nil:NilClass (NoMethodError)
	from /shared/rdoc/lib/rdoc/markdown.rb:797:in `each'
	from /shared/rdoc/lib/rdoc/markdown.rb:797:in `each_with_index'
	from /shared/rdoc/lib/rdoc/markdown.rb:797:in `parse'
	from /shared/rdoc/lib/rdoc/markdown.rb:621:in `parse'
	from tst.rb:10:in `<main>'
```

## Example input
```
^[[^[]]
```

## Explanation

In the main `parse` method, `@footnotes[ref]` to returns nil, and then the call to `note.parts.unshift` results in an unhandled `NoMethodError`.

**Comment by skatkov** [comment]
I tried to reproduce this issue with a current master branch, but was unable.

With following test in `test/rdoc/rdoc_markdown_test.rb` file:

```ruby
def test_parse_note_missing_reference
  @parser.notes = true

  error = assert_raise RDoc::Markdown::ParseError do
    parse "^[[^[]]"
  end

  assert_equal "footnote [^[] not found", error.message
end
```

Rdoc returns `RDoc::Markdown::ParseError`, instead of the mentioned `NoMethodError`. 

This seems already fixed?

**Comment by kou** [comment]
Thanks. I close this.
