### ISSUE TITLE
Missing file from specifications causing build failures

### ISSUE THREAD

**Issue by poloka** [ruby/rdoc#681]
With release of 6.1.0, started getting errors during my site generation.  Cannot seem to load a file `rdoc/markup/regexp_handling` which looks to be introduced with the update
https://github.com/ruby/rdoc/compare/v6.0.4..v6.1.0

Troubleshooted by locking in 6.0.4 and I can create my site doc.

Upon investigating, discovered the regexp_handling.rb was not in the list of loaded files within the specification.  Will submit a PR.

```
Generating Darkfish format into /Users/poloka/temp/foo_service/target/doc...
rake aborted!
LoadError: cannot load such file -- rdoc/markup/regexp_handling
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `block in require'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:257:in `load_dependency'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/attribute_manager.rb:319:in `split_into_flow'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/attribute_manager.rb:261:in `flow'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/to_html.rb:400:in `to_html'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/to_html.rb:189:in `accept_paragraph'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/paragraph.rb:11:in `accept'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/formatter.rb:75:in `block in accept_document'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/formatter.rb:70:in `each'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/formatter.rb:70:in `accept_document'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/formatter.rb:73:in `block in accept_document'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/formatter.rb:70:in `each'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/formatter.rb:70:in `accept_document'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/markup/document.rb:68:in `accept'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/text.rb:105:in `markup'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/markup.rb:132:in `description'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/template/darkfish/class.rhtml:51:in `block in generate_class'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:753:in `template_result'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:732:in `block in render_template'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:727:in `open'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:727:in `open'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:727:in `render_template'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:356:in `generate_class'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:382:in `block in generate_class_files'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:379:in `each'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:379:in `generate_class_files'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/generator/darkfish.rb:246:in `generate'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/rdoc.rb:528:in `block in generate'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/rdoc.rb:523:in `chdir'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/rdoc.rb:523:in `generate'
/Users/poloka/.rvm/gems/ruby-2.4.1@foo_service/gems/rdoc-6.1.0/lib/rdoc/rdoc.rb:502:in `document'
```

**Comment by poloka** [comment]
PR: https://github.com/ruby/rdoc/pull/682

**Comment by poloka** [comment]
@aycabta if you could, release a 6.1.1 version with this fix once its been merged.  Expecting all rdoc site generations to be broken until its added.

**Comment by aycabta** [comment]
Thank you!
