### ISSUE TITLE
RDoc 6.1.1 fails to parse docs for YARD 0.9.18

### ISSUE THREAD

**Issue by dklotz** [ruby/rdoc#694]
This error was originally filed against yard here: https://github.com/lsegal/yard/issues/1218

The assumption there was that this is probably a bug in rdoc, so I'm reporting it here.

Steps to reproduce:
```
$ rdoc --version
6.1.1
$ gem install yard
--------------------------------------------------------------------------------
As of YARD v0.9.2:

RubyGems "--document=yri,yard" hooks are now supported. You can auto-configure
YARD to automatically build the yri index for installed gems by typing:

    $ yard config --gem-install-yri

See `yard config --help` for more information on RubyGems install hooks.

You can also add the following to your .gemspec to have YARD document your gem
on install:

    spec.metadata["yard.run"] = "yri" # use "yard" to build full HTML docs.

--------------------------------------------------------------------------------
Successfully installed yard-0.9.18
Building YARD (yri) index for yard-0.9.18...
Parsing documentation for yard-0.9.18
Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/local/opt/ruby/bin/ruby -c lib/yard/i18n/pot_generator.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

	(NoMethodError) undefined method `[]' for nil:NilClass

ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
```

Full debug trace from the original issue: https://gist.github.com/dklotz/a468eba42d2dcf6c0b20b4233232268e

The file in question is probably this [pot_generator.rb](https://github.com/lsegal/yard/blob/v0.9.18/lib/yard/i18n/pot_generator.rb) from YARD.

**Comment by majioa** [comment]
And what is backtrace log for the error?

**Comment by dklotz** [comment]
@majioa This is the backtrace (it was linked in the gist in the report):
```
Exception `NoMethodError' at /Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rdoc.rb:398 - undefined method `[]' for nil:NilClass
ERROR:  While executing gem ... (NoMethodError)
    undefined method `[]' for nil:NilClass
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/parser/ripper_state_lex.rb:496:in `heredoc_end?'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/parser/ripper_state_lex.rb:473:in `get_heredoc_tk'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/parser/ripper_state_lex.rb:346:in `get_squashed_tk'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/parser/ripper_state_lex.rb:578:in `parse'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/parser/ruby.rb:180:in `initialize'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/parser.rb:191:in `new'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/parser.rb:191:in `for'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rdoc.rb:360:in `parse_file'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rdoc.rb:416:in `block in parse_files'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rdoc.rb:414:in `map'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rdoc.rb:414:in `parse_files'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rubygems_hook.rb:190:in `block in generate'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rubygems_hook.rb:189:in `chdir'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rubygems_hook.rb:189:in `generate'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rubygems_hook.rb:56:in `block in generation_hook'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rubygems_hook.rb:55:in `each'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/rdoc-6.1.1/lib/rdoc/rubygems_hook.rb:55:in `generation_hook'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/request_set.rb:323:in `block in install_hooks'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/request_set.rb:322:in `each'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/request_set.rb:322:in `install_hooks'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/request_set.rb:221:in `install'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/commands/install_command.rb:212:in `install_gem'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/commands/install_command.rb:264:in `block in install_gems'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/commands/install_command.rb:258:in `each'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/commands/install_command.rb:258:in `install_gems'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/commands/install_command.rb:165:in `execute'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/command.rb:321:in `invoke_with_build_args'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/command_manager.rb:176:in `process_args'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/command_manager.rb:146:in `run'
	/Users/david.klotz/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/gem_runner.rb:59:in `run'
	/Users/david.klotz/.rbenv/versions/2.6.0/bin/gem:21:in `<main>'
```
