### ISSUE TITLE
RDoc (6.0.1) Error undefined method `path=' for #<WEBrick::HTTPRequest:0x00007fcf09a02f78>

### ISSUE THREAD

**Issue by tavaresc** [ruby/rdoc#713]
(Not sure if it is a bug...)
-- Error message:
>While processing http://localhost:8808/doc_root/bundler-2.0.1/ the RDoc (6.0.1) server has encountered a NoMethodError exception:
>
>undefined method `path=' for #<WEBrick::HTTPRequest:0x00007fcf09a02f78>
>Did you mean?  path

-- Backtrace:
>/Users/cta/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rdoc/servlet.rb:114:in `do_GET'
>/Users/cta/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpservlet/abstract.rb:105:in `service'
>/Users/cta/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
>/Users/cta/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
>/Users/cta/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'

**Comment by tavaresc** [comment]
Issue closed because already fixed in #587
